### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by zubietaroberto** [vechain/web3-gear#12]
Using a Python 3.5 venv on Elemenentary Linux Freyja (Downtream from Ubuntu).

I am missing the "Blake2b" dependency.

```bash
(venv3) zubietaroberto@Titania:~$ pip install web3-gear
Collecting web3-gear
...
Successfully installed bitcoin-1.1.42 certifi-2018.4.16 cffi-1.11.5 chardet-3.0.4 cytoolz-0.9.0.1 eth-hash-0.1.4 eth-utils-1.0.3 idna-2.7 json-rpc-1.11.0 lru-dict-1.1.6 pbkdf2-1.3 pycparser-2.18 pycryptodome-3.6.4 requests-2.19.1 rlp-0.6.0 scrypt-0.8.6 secp256k1-0.13.2 toolz-0.9.0 urllib3-1.23 web3-gear-1.0.8 werkzeug-0.14.1
(venv3) zubietaroberto@Titania:~$ web3-gear
Traceback (most recent call last):
  File "/home/zubietaroberto/venv3/bin/web3-gear", line 7, in <module>
    from gear.cli import run_server
  File "/home/zubietaroberto/venv3/lib/python3.5/site-packages/gear/cli.py", line 5, in <module>
    from .thor.client import thor
  File "/home/zubietaroberto/venv3/lib/python3.5/site-packages/gear/thor/client.py", line 9, in <module>
    from gear.utils.compat import (
  File "/home/zubietaroberto/venv3/lib/python3.5/site-packages/gear/utils/compat.py", line 4, in <module>
    from hashlib import blake2b
ImportError: cannot import name 'blake2b'
```

**Comment by uldaman** [comment]
Please update python to 3.6, reference: [add BLAKE2 to hashlib](https://bugs.python.org/issue26798)

**Comment by zubietaroberto** [comment]
Updated to Python 3.7. It worked.
