### ISSUE TITLE
Not working with truffle V5 yet

### ISSUE THREAD

**Issue by duongvansang** [vechain/web3-gear#15]
When I try with truffle migrate with truffle V5, I got these error

truffle migrate
Error: Returned error: Method not found
    at Object.ErrorResponse (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/web3-core-helpers/src/errors.js:29:1)
    at /opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/ganache-core/~/web3-core-requestmanager/src/index.js:140:1
    at /opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/web3-providers-http/src
    at XMLHttpRequestEventTarget.dispatchEvent (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-htt
target.js:34:1)
    at XMLHttpRequest._setReadyState (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.
    at XMLHttpRequest._onHttpResponseEnd (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-requ
    at IncomingMessage.<anonymous> (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Truffle v5.0.2 (core: 5.0.2)
Node v8.11.4

**Comment by uldaman** [comment]
Can you show the output of Web3-gear when the error happened?

**Comment by duongvansang** [comment]
Web3-Gear/1.1.0/linux/python3.6.7
Listening on 127.0.0.1:8545
INFO - gear.rpc[line:138] - received rpc request - eth_accounts
INFO - gear.rpc[line:138] - received rpc request - eth_accounts
INFO - gear.rpc[line:212] - received rpc request - eth_getBlockByNumber
INFO - gear.rpc[line:212] - received rpc request - eth_getBlockByNumber
INFO - gear.rpc[line:144] - received rpc request - eth_getCode
INFO - gear.rpc[line:180] - received rpc request - eth_getBalance

Here is log of web3-gear

**Comment by uldaman** [comment]
There is no keyword similar to "Method not found", is this the log when the error occurred?

**Comment by duongvansang** [comment]
> There is no keyword similar to "Method not found", is this the log when the error occurred?

Yes

**Comment by uldaman** [comment]
I modified some of the code (d5615276577da8d42efe4c0caff367fb34afb0d3), please update and try again.
