### ISSUE TITLE
truffle migrate error

### ISSUE THREAD

**Issue by marcomarasco** [vechain/web3-gear#26]
Hi, i receive the following errors during `truffle migrate`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 22, in wrapper
    result = await func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 271, in eth_getFilterChanges
    return thor.get_filter_changes(filter_id)
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 164, in get_filter_changes
    return func()
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 188, in __call__
    for id in map(self.client.get_block_id, range(self.current, best_num + 1))
TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 22, in wrapper
    result = await func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 271, in eth_getFilterChanges
    return thor.get_filter_changes(filter_id)
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 164, in get_filter_changes
    return func()
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 188, in __call__
    for id in map(self.client.get_block_id, range(self.current, best_num + 1))
TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 22, in wrapper
    result = await func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 271, in eth_getFilterChanges
    return thor.get_filter_changes(filter_id)
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 164, in get_filter_changes
    return func()
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 188, in __call__
    for id in map(self.client.get_block_id, range(self.current, best_num + 1))
TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 22, in wrapper
    result = await func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 271, in eth_getFilterChanges
    return thor.get_filter_changes(filter_id)
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 164, in get_filter_changes
    return func()
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 188, in __call__
    for id in map(self.client.get_block_id, range(self.current, best_num + 1))
TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 22, in wrapper
    result = await func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/gear/rpc.py", line 271, in eth_getFilterChanges
    return thor.get_filter_changes(filter_id)
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 164, in get_filter_changes
    return func()
  File "/usr/local/lib/python3.7/site-packages/gear/thor/client.py", line 188, in __call__
    for id in map(self.client.get_block_id, range(self.current, best_num + 1))
TypeError: unsupported operand type(s) for +: 'coroutine' and 'int'
```

Anyone can help?

**Comment by uldaman** [comment]
Please update to the latest version, it was fixed this bug.

**Comment by marcomarasco** [comment]
It works!
