### ISSUE TITLE
Truffle hangs on 'migrations' 

### ISSUE THREAD

**Issue by luukfroling** [vechain/web3-gear#40]
While running 
">web3-gear --host 127.0.0.1 --port 8545 --endpoint https://sync-testnet.vechain.org --keystore ./keystore --passcode password"
in one cmd, I am trying to run 
"npx truffle migrate --network testnet" 
in another cmd window. (according to [)](https://medium.com/coinmonks/create-and-deploy-smart-contracts-on-vechain-bf1c94cdb776) )

The server does not display any error messages. The server displays just this:

` Web3-Gear/2.0.2/win32/python3.9.8
Listening on 127.0.0.1:8545
======== Running on http://127.0.0.1:8545 ========
(Press CTRL+C to quit) `

The client, where I am trying to migrate the smart contract using truffle hangs. This is the output:

(I have been trying to get the markup right, but something is going wrong. This is the start of the console output)
`
Compiling your contracts...
===========================
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\contract.sol
> Artifacts written to C:\Users\luukf\Documents\blockchain prototypes\build\contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

Starting migrations...
======================
> Network name:    testnet
> Network id:      5777
> Block gas limit: 21000000 (0x1406f40)

1_initial_migration.js
======================

   Deploying Migrations
   ----------------------
` (and here it ends)

where it will keep hanging. Upon pressing ctrl+c to exit, it throws this error:

`UnhandledRejections detected
Terminate batch job (Y/N)? Promise {
  <rejected> Error: Returned error: Method not found
      at Object.ErrorResponse (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3-core-helpers\lib\errors.js:28:1)
      at C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3\node_modules\web3-core-requestmanager\lib\index.js:302:1
      at C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3\node_modules\web3-providers-http\lib\index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:289:47)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    data: null
  }
} Error: Returned error: Method not found
    at Object.ErrorResponse (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3-core-helpers\lib\errors.js:28:1)
    at C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3\node_modules\web3-core-requestmanager\lib\index.js:302:1
    at C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\wrapper.js:107:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\web3\node_modules\web3-providers-http\lib\index.js:98:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:208:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (C:\Users\luukf\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\xhr2-cookies\dist\xml-http-request.js:289:47)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: null
}`

This message will keep repeating itself, the longer I leave the program hanging to more times it will be displayed upon exiting the program. Any solution to fix this?

**Comment by dennohpeter** [comment]
Stack at the same issue too any fix, or workaround ?

**Comment by lopeselio** [comment]
Can someone help with this issue @libotony ?
